# Generated by Django 5.1.1 on 2024-09-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoscategorias',
            name='tipo',
        ),
        migrations.AddField(
            model_name='autoscategorias',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=10),
        ),
    ]
