# Generated by Django 5.1.1 on 2024-09-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='año',
            new_name='ano',
        ),
    ]
