# Generated by Django 5.1.1 on 2024-09-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_auto_fecha_actualizacion_auto_precio_auto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='auto',
            index=models.Index(fields=['modelo'], name='autos_auto_modelo_1a394e_idx'),
        ),
        migrations.AddConstraint(
            model_name='auto',
            constraint=models.UniqueConstraint(fields=('modelo', 'ano'), name='modelo_ano'),
        ),
    ]
