# Generated by Django 5.1.1 on 2024-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_auto_imagen_auto_autos_auto_modelo_1a394e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Rojo Perla', 'Rojo Perla'), ('Azul Marino', 'Azul Marino'), ('Amarillo', 'Amarillo'), ('Blanco Perla', 'Blanco Perla'), ('Verde Militar', 'Verde Militar'), ('Gris Plata', 'Gris Plata'), ('Rojo Carmin', 'Rojo Carmin'), ('Azul Noche', 'Azul Noche'), ('Plata Metalizado', 'Plata Metalizado')], max_length=20),
        ),
    ]
